version: "3"
services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - 3030:5432
    environment:
      - POSTGRESQL_USERNAME=alison
      - POSTGRESQL_PASSWORD=alison123
      - POSTGRESQL_DATABASE=chats
    volumes:
      - "./data:/bitnami/postgresql"
